# Generated by Django 5.1.3 on 2024-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_price_transaction_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='raw_material',
            field=models.CharField(max_length=100),
        ),
    ]
